language: objective-c
osx_image: xcode10.1
xcode_project: AGCustomControls.xcodeproj
xcode_scheme: AGCustomControlsTests
branches:
  only:
  - master
script:
  xcodebuild -project AGCustomControls.xcodeproj -scheme AGCustomControlsTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
